version: "3.9"
services:
  web:
    build: web
    command: ./start_server.sh "${statedir}" "${TMPDIR}"
    volumes:
      - "./web:/app:ro"
      - "${TMPDIR}:${TMPDIR}"
      - "${statedir}:${statedir}"
  bot:
    build: bot
    command: ./start_server.sh "${statedir}" "${TMPDIR}"
    volumes:
      - "./bot:/app:ro"
      - "${TMPDIR}:${TMPDIR}"
      - "${statedir}:${statedir}"
networks:
  default:
    internal: false
