category: reverse
points: 150
title: similar to crypto, but...
description: >
  Мы нашли подозрительную флешку, на которой было всего два файла. Похоже, один
  из них — программа для шифрования, которой зашифрован второй файл.
flags:
- kettle_4ma0_k0mar0va_10v3rs_01eg
attachments_path: attachments
