version: "3.9"
services:
  web:
    build: .
    command: ./start_server.sh "${statedir}" "${TMPDIR}"
    volumes:
      - ".:/pastehex:ro"
      - "${TMPDIR}:${TMPDIR}"
      - "${statedir}:${statedir}"
networks:
  default:
    internal: true